export const GAME_ACTIONS = {
    RECEIVE_ACTION: "RECEIVE_ACTION",
    SEND_ACTION: "SEND_ACTION",
    WAITING_PLAYER: "WAITING_PLAYER",
    WAITING_CARDS: "WAITING_CARDS",
    END_TURN: "END_TURN",
    START_TURN: "START_TURN",
    GAME_STARTS: "GAME_STARTS",
    CARD_SELECTION: "CARD_SELECTION",
    ACTION_SUCCESS: "ACTION_SUCCESS",
    ACTION_FAILED: "ACTION_FAILED",
    GAME_OVER: "GAME_OVER",
};
